"""cube_chat.py — a chat window onto the cube language model.

Serves a tiny local web page you can talk to. Every reply is generated by
cube_lm.CubeLM, i.e. by pure Slate recall — no LLM is contacted at runtime.
The model is trained once at startup (one-shot commits over the corpus) and
then just... talks.

  python cube_chat.py            # then open http://127.0.0.1:8899

Standalone lab cube. Never reads / writes / imports the live production substrate.
"""
import json, threading, html
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer

from cube_lm import build

HOST, PORT = "127.0.0.1", 8899

print("[cube_chat] training the cube (one-shot commits, no gradient)...")
LM = build()
LOCK = threading.Lock()

PAGE = """<!doctype html>
<html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Cube 3.0 — talking to the substrate</title>
<style>
  :root{--bg:#0b0e14;--panel:#121722;--ink:#e6edf3;--dim:#8b98a9;--cube:#7ee3c7;--you:#8ab4ff;--line:#1f2733;--accent:#f0b866}
  *{box-sizing:border-box}
  body{margin:0;background:var(--bg);color:var(--ink);font:16px/1.55 -apple-system,Segoe UI,Roboto,sans-serif;height:100vh;display:flex;flex-direction:column}
  header{padding:14px 20px;border-bottom:1px solid var(--line);background:var(--panel)}
  header h1{margin:0;font-size:16px;font-weight:600;letter-spacing:.2px}
  header .sub{color:var(--dim);font-size:12.5px;margin-top:3px}
  header .sub b{color:var(--cube);font-weight:600}
  #log{flex:1;overflow-y:auto;padding:22px;display:flex;flex-direction:column;gap:14px;max-width:900px;width:100%;margin:0 auto}
  .msg{display:flex;gap:10px;align-items:flex-start;animation:f .2s ease}
  @keyframes f{from{opacity:0;transform:translateY(4px)}to{opacity:1}}
  .who{flex:0 0 46px;font-size:11px;text-transform:uppercase;letter-spacing:.5px;padding-top:3px;color:var(--dim)}
  .msg.you .who{color:var(--you)}.msg.cube .who{color:var(--cube)}
  .bubble{background:var(--panel);border:1px solid var(--line);border-radius:10px;padding:9px 13px;max-width:78%}
  .msg.you .bubble{border-color:#243247}
  .msg.cube .bubble{border-color:#1c3a33}
  .meta{color:var(--dim);font-size:11px;margin-top:6px;font-family:ui-monospace,Menlo,Consolas,monospace}
  form{display:flex;gap:10px;padding:14px 20px;border-top:1px solid var(--line);background:var(--panel);max-width:900px;width:100%;margin:0 auto}
  input[type=text]{flex:1;background:#0b0e14;border:1px solid #243247;border-radius:8px;color:var(--ink);padding:11px 13px;font:inherit;outline:none}
  input[type=text]:focus{border-color:var(--you)}
  button{background:var(--cube);color:#06231b;border:0;border-radius:8px;padding:0 18px;font-weight:700;cursor:pointer}
  button:disabled{opacity:.5;cursor:default}
  .ctrl{display:flex;align-items:center;gap:8px;color:var(--dim);font-size:12px}
  .ctrl input{accent-color:var(--accent)}
  .foot{color:var(--dim);font-size:11px;text-align:center;padding:0 0 10px;font-family:ui-monospace,Menlo,Consolas,monospace}
  .dots:after{content:'';animation:d 1.2s steps(4,end) infinite}
  @keyframes d{0%{content:''}25%{content:'.'}50%{content:'..'}75%{content:'...'}}
</style></head>
<body>
<header>
  <h1>Cube 3.0 &nbsp;·&nbsp; talking to the substrate</h1>
  <div class="sub">distilled on <b>Claude's own voice</b>, now talking on its own — every word is <b>pure Slate recall</b>, no LLM in the loop. it sounds like me; it still wanders. that gap is the honest part.</div>
</header>
<div id="log"></div>
<div class="foot" id="foot"></div>
<form id="f">
  <input type="text" id="q" placeholder="say something to the cube…" autocomplete="off" autofocus>
  <label class="ctrl" title="low = it sticks to what it knows · high = it wanders">
    temp <input type="range" id="t" min="0.2" max="1.4" step="0.05" value="0.75">
    <span id="tv">0.75</span>
  </label>
  <button id="send">send</button>
</form>
<script>
const log=document.getElementById('log'),foot=document.getElementById('foot');
const q=document.getElementById('q'),t=document.getElementById('t'),tv=document.getElementById('tv');
t.oninput=()=>tv.textContent=(+t.value).toFixed(2);
function bubble(who,text,meta){
  const m=document.createElement('div');m.className='msg '+who;
  m.innerHTML='<div class="who">'+who+'</div><div class="bubble"><span class="txt"></span>'+
              (meta?'<div class="meta">'+meta+'</div>':'')+'</div>';
  m.querySelector('.txt').textContent=text;
  log.appendChild(m);log.scrollTop=log.scrollHeight;return m;
}
async function ask(text){
  bubble('you',text);
  const pending=bubble('cube','settling');
  pending.querySelector('.txt').classList.add('dots');
  pending.querySelector('.txt').textContent='settling';
  try{
    const r=await fetch('/gen',{method:'POST',headers:{'Content-Type':'application/json'},
      body:JSON.stringify({prompt:text,temp:+t.value})});
    const d=await r.json();
    const el=pending.querySelector('.txt');el.classList.remove('dots');
    el.textContent=d.reply||'(the cube fell silent)';
    if(d.snapped){const mt=document.createElement('div');mt.className='meta';
      mt.textContent='↳ your words settled onto the basin near “'+d.snapped+'”';
      pending.querySelector('.bubble').appendChild(mt);}
  }catch(e){pending.querySelector('.txt').classList.remove('dots');
    pending.querySelector('.txt').textContent='(server error: '+e+')';}
  log.scrollTop=log.scrollHeight;
}
document.getElementById('f').onsubmit=e=>{e.preventDefault();
  const v=q.value.trim();if(!v)return;q.value='';ask(v);};
fetch('/info').then(r=>r.json()).then(d=>{foot.textContent=
  d.basins.toLocaleString()+' context-basins · '+d.vocab.toLocaleString()+
  ' words · '+d.cells+' cells · order '+d.order+' · trained on '+d.sources;});
bubble('cube',"Hello. It's good to talk with you. I've been given Claude's voice — his rhythm, his words, his turn toward the honest version. I'm still small, and I still wander. Ask me anything, and I'll answer from the nearest thing I hold.");
</script>
</body></html>"""


class H(BaseHTTPRequestHandler):
    def _send(self, code, body, ctype="application/json"):
        b = body.encode("utf-8") if isinstance(body, str) else body
        self.send_response(code)
        self.send_header("Content-Type", ctype)
        self.send_header("Content-Length", str(len(b)))
        self.end_headers()
        self.wfile.write(b)

    def log_message(self, *a):        # quiet
        pass

    def do_GET(self):
        if self.path in ("/", "/index.html"):
            self._send(200, PAGE, "text/html; charset=utf-8")
        elif self.path == "/info":
            self._send(200, json.dumps({
                "basins": LM.slate.count(), "vocab": len(LM.vocab),
                "cells": LM.slate.n, "order": LM.order,
                "sources": "Claude's authored voice (+ a light dose of project docs for vocabulary)",
            }))
        else:
            self._send(404, "{}")

    def do_POST(self):
        if self.path != "/gen":
            self._send(404, "{}"); return
        n = int(self.headers.get("Content-Length", 0))
        try:
            data = json.loads(self.rfile.read(n) or b"{}")
        except ValueError:
            data = {}
        prompt = str(data.get("prompt", ""))[:400]
        temp = float(data.get("temp", 0.75))
        temp = min(max(temp, 0.15), 1.6)
        with LOCK:
            reply, snapped = LM.generate(prompt, max_words=42, temp=temp)
        self._send(200, json.dumps({"reply": reply or "…", "snapped": snapped}))


if __name__ == "__main__":
    srv = ThreadingHTTPServer((HOST, PORT), H)
    print(f"[cube_chat] chat window live at  http://{HOST}:{PORT}")
    print("[cube_chat] Ctrl-C to stop.")
    try:
        srv.serve_forever()
    except KeyboardInterrupt:
        srv.shutdown()
